#!/bin/bash
# Frontend Provisioning Script for Infinibay
# This script installs Node.js and sets up the Next.js frontend

set -e

echo "=== Frontend Provisioning ==="

# Update package lists
apt-get update

# Install dependencies
echo "Installing dependencies..."
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    build-essential

# Clone Infinibay frontend repository
echo "Cloning Infinibay frontend repository..."
mkdir -p /opt/infinibay
chmod 755 /opt/infinibay

# Configure git to trust Infinibay directories
git config --global --add safe.directory /opt/infinibay/frontend

if [ ! -d /opt/infinibay/frontend/.git ]; then
    echo "Cloning frontend repository..."
    git clone https://github.com/Infinibay/frontend.git /opt/infinibay/frontend
    chmod -R 755 /opt/infinibay/frontend
else
    echo "Frontend repository already exists, pulling latest changes..."
    cd /opt/infinibay/frontend && git pull
fi

echo "✓ Frontend repository cloned successfully"

# Install Node.js 20.x (LTS)
echo "Installing Node.js 20.x..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

# Verify installation
node --version
npm --version

# Create infinibay user if it doesn't exist
if ! id -u infinibay > /dev/null 2>&1; then
    useradd -m -s /bin/bash infinibay
fi

# Set up directories
# Create subdirectories for frontend data
mkdir -p /data/logs /data/cache
chown -R infinibay:infinibay /data/logs /data/cache

# Install PM2 for process management
echo "Installing PM2..."
npm install -g pm2

# Create PM2 startup script
cat > /usr/local/bin/infinibay-frontend << 'EOF'
#!/bin/bash
cd /opt/infinibay/frontend
exec su - infinibay -c "cd /opt/infinibay/frontend && npm run dev"
EOF

chmod +x /usr/local/bin/infinibay-frontend

# Create systemd service
cat > /etc/systemd/system/infinibay-frontend.service << 'EOF'
[Unit]
Description=Infinibay Frontend (Next.js)
After=network.target

[Service]
Type=simple
User=infinibay
WorkingDirectory=/opt/infinibay/frontend
Environment=NODE_ENV=production
Environment=PORT=3000
ExecStart=/usr/bin/npm run start
Restart=always
RestartSec=10
StandardOutput=append:/data/logs/frontend.log
StandardError=append:/data/logs/frontend-error.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

# ============================================================================
# Section 1: Environment Configuration
# ============================================================================

echo "Creating frontend .env file..."

# Verify frontend directory exists and is writable
if [ ! -d /opt/infinibay/frontend ]; then
    echo "✗ ERROR: /opt/infinibay/frontend directory does not exist!"
    exit 1
fi

# Ensure directory is writable
chmod 755 /opt/infinibay/frontend
echo "Frontend directory permissions: $(ls -ld /opt/infinibay/frontend)"

# Use BACKEND_IP environment variable passed from provisioning script
# If not set, fallback to hostname
if [ -z "$BACKEND_IP" ]; then
    echo "⚠ WARNING: BACKEND_IP not provided, using hostname fallback"
    BACKEND_IP="infinibay-backend"
else
    echo "✓ Using backend IP: $BACKEND_IP"
fi

# Create frontend .env file with LXD container networking
cat > /opt/infinibay/frontend/.env << EOF
# Frontend Environment Configuration
# Auto-generated by provisioning script

# GraphQL API endpoint (using backend container IP)
NEXT_PUBLIC_GRAPHQL_API_URL=http://${BACKEND_IP}:4000/graphql

# Backend host for WebSocket and API rewrites
NEXT_PUBLIC_BACKEND_HOST=http://${BACKEND_IP}:4000

# Node environment
NODE_ENV=production

# Frontend server port
PORT=3000
EOF

# Set proper ownership and permissions
chown infinibay:infinibay /opt/infinibay/frontend/.env
chmod 600 /opt/infinibay/frontend/.env

echo "✓ Frontend .env file created"

# ============================================================================
# Section 2: Dependency Installation
# ============================================================================

echo "Installing frontend dependencies..."

# Change ownership to infinibay user
chown -R infinibay:infinibay /opt/infinibay/frontend

# Install dependencies as infinibay user
# Note: We need devDependencies for the build step, but skip git hooks (husky)
su - infinibay -c "cd /opt/infinibay/frontend && HUSKY=0 npm install"

# Count installed packages
PACKAGE_COUNT=$(cd /opt/infinibay/frontend && npm list --depth=0 2>/dev/null | grep -c "├\|└" || echo "unknown")

echo "✓ Frontend dependencies installed ($PACKAGE_COUNT packages)"

# ============================================================================
# Section 3: Production Build
# ============================================================================

echo "Building frontend for production (this may take a few minutes)..."

# Run production build as infinibay user (temporarily disable set -e to capture exit code)
set +e
su - infinibay -c "cd /opt/infinibay/frontend && npm run build"
BUILD_EXIT_CODE=$?
set -e

if [ $BUILD_EXIT_CODE -ne 0 ]; then
    echo "✗ ERROR: Frontend build failed!"
    echo ""
    echo "Troubleshooting steps:"
    echo "  1. Verify Node.js version: node --version (should be 20.x)"
    echo "  2. Check environment variables in /opt/infinibay/frontend/.env"
    echo "  3. Verify dependencies installed: ls -la /opt/infinibay/frontend/node_modules"
    echo "  4. Try manual build: cd /opt/infinibay/frontend && npm run build"
    echo ""
    exit 1
fi

# Verify build directory exists
if [ -d /opt/infinibay/frontend/.next ]; then
    BUILD_SIZE=$(du -sh /opt/infinibay/frontend/.next | cut -f1)
    echo "✓ Frontend built successfully (build size: $BUILD_SIZE)"
else
    echo "✗ ERROR: Build directory .next not found!"
    exit 1
fi

# ============================================================================
# Section 4: Service Startup
# ============================================================================

echo "Starting infinibay-frontend service..."

# Enable service to start on boot
systemctl enable infinibay-frontend

# Start the service
systemctl start infinibay-frontend

# Wait for service to become active (30 second timeout)
echo "Waiting for frontend service to start..."
SERVICE_STARTED=false
for i in {1..30}; do
    if systemctl is-active --quiet infinibay-frontend; then
        echo "✓ Frontend service is running"
        SERVICE_STARTED=true
        break
    fi
    sleep 1
done

if [ "$SERVICE_STARTED" = false ]; then
    echo "⚠ WARNING: Frontend service did not start within 30 seconds"
    echo "   Check service status manually: systemctl status infinibay-frontend"
fi

# Display service status for debugging
echo ""
echo "Service status:"
systemctl status infinibay-frontend --no-pager || true

# ============================================================================
# Section 5: Completion
# ============================================================================

echo ""
echo "Frontend provisioning completed!"
echo "Node.js version: $(node --version)"
echo "npm version: $(npm --version)"
echo ""
echo "Service has been started and enabled to run on boot."
echo ""
echo "Logs: /data/logs/frontend.log"
